-- FleetTrack initial schema.
-- Multi-tenant: every business row carries organization_id. The app talks to
-- Postgres server-side only (DATABASE_URL); RLS is enabled with no policies so
-- the Supabase anon/authenticated keys can read nothing.

create extension if not exists pgcrypto;

create table if not exists organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  currency text not null default 'KES',
  status text not null default 'active' check (status in ('active','suspended')),
  phone text,
  email text,
  logo_url text,
  tagline text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references organizations(id) on delete cascade,
  email text not null,
  password_hash text not null,
  full_name text not null,
  phone text,
  -- owner: everything; manager: everything but team/org settings;
  -- recorder: (driver/conductor/clerk) records entries for assigned vehicles.
  role text not null default 'recorder' check (role in ('owner','manager','recorder')),
  is_super_admin boolean not null default false,
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists users_email_key on users (lower(email));
create index if not exists users_org_idx on users (organization_id);

create table if not exists vehicles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  registration text not null,
  nickname text,
  make_model text,
  capacity int,
  sacco text,
  route text,
  status text not null default 'active' check (status in ('active','inactive')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create unique index if not exists vehicles_org_reg_key
  on vehicles (organization_id, upper(registration)) where deleted_at is null;

-- Recorders only see/record for vehicles they are assigned to.
create table if not exists user_vehicles (
  user_id uuid not null references users(id) on delete cascade,
  vehicle_id uuid not null references vehicles(id) on delete cascade,
  primary key (user_id, vehicle_id)
);

create table if not exists expense_categories (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  name text not null,
  -- daily: recorded on each day's entry (fuel, sacco, driver...)
  -- fixed: recorded once a month (insurance, service, wages...)
  kind text not null check (kind in ('daily','fixed')),
  -- Optional reporting tag so dashboards can surface specific KPIs
  -- (driver payments, wages to other employees, tithe).
  tag text check (tag in ('driver','wages','tithe')),
  sort_order int not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists expense_categories_org_name_key
  on expense_categories (organization_id, lower(name), kind);

create table if not exists daily_entries (
  -- id may be generated by the client (offline-first Android) so a retried
  -- upload is idempotent.
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  vehicle_id uuid not null references vehicles(id) on delete cascade,
  entry_date date not null,
  income numeric(12,2) not null default 0 check (income >= 0),
  parcels numeric(12,2) not null default 0 check (parcels >= 0),
  notes text,
  recorded_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create unique index if not exists daily_entries_vehicle_date_key
  on daily_entries (vehicle_id, entry_date) where deleted_at is null;
create index if not exists daily_entries_org_date_idx on daily_entries (organization_id, entry_date);

create table if not exists daily_entry_expenses (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references daily_entries(id) on delete cascade,
  category_id uuid not null references expense_categories(id) on delete restrict,
  amount numeric(12,2) not null check (amount >= 0)
);
create index if not exists daily_entry_expenses_entry_idx on daily_entry_expenses (entry_id);

create table if not exists fixed_expenses (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  -- null = applies to the whole fleet, not one vehicle
  vehicle_id uuid references vehicles(id) on delete cascade,
  category_id uuid not null references expense_categories(id) on delete restrict,
  month date not null check (extract(day from month) = 1),
  amount numeric(12,2) not null check (amount >= 0),
  description text,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists fixed_expenses_org_month_idx on fixed_expenses (organization_id, month);

create table if not exists schema_migrations (
  name text primary key,
  applied_at timestamptz not null default now()
);

alter table organizations enable row level security;
alter table users enable row level security;
alter table vehicles enable row level security;
alter table user_vehicles enable row level security;
alter table expense_categories enable row level security;
alter table daily_entries enable row level security;
alter table daily_entry_expenses enable row level security;
alter table fixed_expenses enable row level security;
alter table schema_migrations enable row level security;
